### ISSUE TITLE
many icon suggestions

### ISSUE THREAD

**Issue by Findus23** [alrra/browser-logos#113]
Hi, while renewing the icons in [piwik](https://github.com/piwik/piwik/) (an open source, self-hosted Google Analytics alternative) a few months ago I didn't know about this repo and made an own collection of browser icons. Thanks to a comment I found your repository and have now replaced the icons (because there is no need to duplicate the effort)

There are some icons left, that are missing in your repo: https://github.com/piwik/piwik-icons/tree/alrra-browser-logos/src/browsers

If you are interested I can write a list of icons.

**Comment by alrra** [comment]
> There are some icons left, that are missing in your repo:

That's usually because nobody found/created a good (`512x512px` or bigger) version of those logos. 

> If you are interested I can write a list of icons.

There was a [similar issue](https://github.com/alrra/browser-logos/issues/44), but unfortunately, it proved to not be very useful. So, the project relies on people opening pull requests when they find a decent version of a logo not included yet.

---

> https://github.com/piwik/piwik-icons/blob/0b7fd6e6bcf26e30b0b4ec49cdcdca280b4c9a5e/src/browsers/PM.png

This project also has the [Pale Moon logo](https://github.com/alrra/browser-logos/tree/a521253a87e3e90bd08bb0d8ab53745f3d65b6a2/src/pale-moon).

**Comment by Findus23** [comment]
You are right. For many of them high resolution icons are hard to find.

But three of them have a high resolution icon:

## Google Earth 
While not a browser it sends its own user agent.
![](https://upload.wikimedia.org/wikipedia/commons/f/f0/Google_Earth_Icon.png)
https://commons.wikimedia.org/wiki/File:Google_Earth_Icon.png

## Jasmine
![](https://github.com/piwik/piwik-icons/blob/master/src/browsers/JS.png?raw=true)
https://github.com/jasmine/jasmine.github.io/blob/5ce975d2eb0a254997589897c5aefdbf5f9b070c/images/jasmine_vertical.svg

## Streamy
![https://www.streamybrowser.com/images/logo.svg](https://www.streamybrowser.com/images/logo.svg
)
https://www.streamybrowser.com/images/logo.svg

**Comment by alrra** [comment]
> While not a browser it sends its own user agent.

@Findus23 Sorry, will only accept browser logos.

---

> But three of them have a high resolution icon:

Added `Streamy`. Thanks!

**Comment by Findus23** [comment]
No problem. I'll just keep the rest in my repo.
