### ISSUE TITLE
Changing branch to main broke every direct link

### ISSUE THREAD

**Issue by SuperSandro2000** [alrra/browser-logos#185]
Your decision to switch the default branch to main without any redirection broke direct linking to images. This probably affects many more people who used  direct links in readmes instead of js packages.

https://github.com/codimd/server/blob/e46d520ca234c05cfe2431c5b7ab61b96194962e/README.md#browser-support

**Comment by alrra** [comment]
@SuperSandro2000 Linking directly to GitHub and not even to a specific commit, has never been a good idea. [Things are moved around all the time](https://github.com/alrra/browser-logos/issues/100), that's why the `README.md` file [specifies some recommended ways](https://github.com/alrra/browser-logos/tree/23fa2d822c0ee423c6f6de54a665da05b386379b#getting-the-browser-logos).

**Comment by SuperSandro2000** [comment]
None of these is really practical for readmes on github. Adding a new entry where you just link to ``HEAD`` instead of master would be a good alternative for such use cases.
