### ISSUE TITLE
Getting error when installing the package

### ISSUE THREAD

**Issue by shashircciit** [alrra/browser-logos#186]
Getting an error when I am doing npm install alrra/browser-logos#67.0.2

npm install alrra/browser-logos
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/alrra/browser-logos.git /Users/xxxxxxx/.npm/_cacache/tmp/git-clone-2d0f0b3d/.git
npm ERR! warning: templates not found in /var/folders/r4/qg022ykn1072fwl32p3wq2ss0kxw08/T/pacote-git-template-tmp/git-clone-58c8a6a7
npm ERR! fatal: protocol error: bad line length character: �200
npm ERR! error: inflate: data stream error (incorrect data check)
npm ERR! fatal: pack has bad object at offset 5251370: inflate returned -3
npm ERR! fatal: index-pack failed
npm ERR! error: RPC failed; curl 56 Malformed encoding found in chunked-encoding
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/xxxxxxx/.npm/_logs/2020-07-15T09_58_06_703Z-debug.log

**Comment by alrra** [comment]
> Getting an error when I am doing npm install #67.0.2

@shashircciit Can you try again? Run:

 `npm install alrra/browser-logos#67.0.2 --loglevel silly` 

(Note: it will take a bit).

If it fails, consider providing more information such as: the output, the content of the `debug.log` file, the `npm` version,  OS information, etc.

Alternatively consider [installing the only the logos you need](https://github.com/alrra/browser-logos#1-get-individual-logos).

---

>  `npm install alrra/browser-logos#67.0.2` 

It takes a bit since it's quite big, but works for me. 🤷
