### ISSUE TITLE
Semantic versions rules?

### ISSUE THREAD

**Issue by Soullivaneuh** [alrra/browser-logos#76]
Could you please add a note about how semantic rules work on this project? 

I was on 3.* and just see you are on v22.

Major version should be BC breaking but nothing indicated about that on the changelog: https://github.com/alrra/browser-logos/blob/22.0.0/CHANGELOG.md

Could you please explain a little bit?

Thanks.

**Comment by alrra** [comment]
> how semantic rules work on this project? ... Could you please explain a little bit?

Sure.

--

> ##### MAJOR version when you make incompatible API changes

Major versions are released every time a path is broken (e.g.: a directory is renamed or moved into  `archive/` without having a replacement). This is done because I consider that to be a breaking change as people who depend on that path will no longer have it.

For example, [`v22.0.0`](https://github.com/alrra/browser-logos/blob/e8f6eaa411da91aaf21949c0bfd63b715dc8a2bb/CHANGELOG.md#2200-february-1-2016) was released because `archive/opera-mini-beta/` was renamed to `archive/opera-mini-beta_1/` since another version of the Opera Mini Beta logo was moved into `archive/` and there was a need to distinguished them.

> ##### MINOR version when you add functionality in a backwards-compatible manner

Minor versions are released mainly when [the SVG version of a logo](https://github.com/alrra/browser-logos/blob/e8f6eaa411da91aaf21949c0bfd63b715dc8a2bb/CHANGELOG.md#870-march-16-2015) and/or [a new logo](https://github.com/alrra/browser-logos/blob/e8f6eaa411da91aaf21949c0bfd63b715dc8a2bb/CHANGELOG.md#2110-january-21-2016) is added.

> ##### PATCH version when you make backwards-compatible bug fixes

Patch versions are released when [typos or links are fixed](https://github.com/alrra/browser-logos/blob/e8f6eaa411da91aaf21949c0bfd63b715dc8a2bb/CHANGELOG.md#1101-july-12-2015), [images are losslessly optimized](https://github.com/alrra/browser-logos/blob/e8f6eaa411da91aaf21949c0bfd63b715dc8a2bb/CHANGELOG.md#1801-november-20-2015), [a better version of a logo is added by just replacing the existing images](https://github.com/alrra/browser-logos/blob/e8f6eaa411da91aaf21949c0bfd63b715dc8a2bb/CHANGELOG.md#503-december-18-2014), etc..

I hope this helps.

--

> I was on 3.* and just see you are on v22.

Yes, things move fast nowadays! :D

**Comment by Soullivaneuh** [comment]
Thanks for the explanation. :-)

I think this should be added on the doc. :+1: 

I completly understand the new major for moving file, but you have to push a lot of them. Why not use a more BC keep method? Let me explain my suggestion: 

Imagine you are on v1.0.x and you want to archive a logo. You could

* Move the logo on the `archive` folder.
* Create a symbolic link of the old file, pointing to the archive folder (git and github manage symlinks like a charm).

Then, the old logo is archived but still accessible from user. Them, you can push v1.1 instead of v2.0.

When you have a lot of deprecated logos and want to clean up, then you can create a new major.

What do you think?

BTW, deleted/moved logos should be marked in the Changelog IMHO.

**Comment by alrra** [comment]
> Create a symbolic link of the old file, pointing to the archive folder... them, you can push v1.1 instead of v2.0.... 

> When you have a lot of deprecated logos and want to clean up, **then you can create a new major**

@Soullivaneuh That would just complicate things a lot without any real benefit as far as I see. Plus, you're just prolonging the inevitable, namely, releasing new `major` versions. Also, given enough time, you will still end up at versions such as `35.y.z`.

> deleted/moved logos should be marked in the Changelog

That is usually stated (e.g.: [Move `X` logo into the `archive/`](https://github.com/alrra/browser-logos/blob/e8f6eaa411da91aaf21949c0bfd63b715dc8a2bb/CHANGELOG.md#2000-december-29-2015)), and if the users want more detailed information, they can just read the commit messages or look at the commits.

**Comment by Soullivaneuh** [comment]
> That would just complicate things a lot without any real benefit as far as I see.

The benefit for user would be to have new update without have to check new majore every week. :-)

> Also, given enough time, you will still end up at versions such as 35.y.z.

Not 35, but a lower number, less major versions...

But I understand, this is harder to maintain, this is just a suggestion. ;-)

**Comment by alrra** [comment]
> have to check new majore every week. :-)

@Soullivaneuh I don't think that's a big problem. From what I've seen, most users only care about the main browsers, and when those browsers update their logos it is usually known, therefore, they will most probably only check / update at that point.

> this is just a suggestion. 

Sure thing, suggestions are always welcomed! :+1:

**Comment by alrra** [comment]
> deleted/moved logos should be marked in the Changelog IMHO.

Updated the [`CHANGELOG.md`](https://github.com/alrra/browser-logos/blob/9f7368e60cd096d38fc8680008aafe9ad9c1412e/CHANGELOG.md) and the [`releases`](https://github.com/alrra/browser-logos/releases). ✨
